name: Makefile CI

on: [push, pull_request]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run unit tests
        run: make test

      - name: Run integration tests
        run: make test-integration
